version: '3'
services:
  database:
    image: postgres
    ports:
      - 9999:5432
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: caveat_emptor
  
  cache:
    image:  redis
    ports:
      - 9998:6379